// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr9dosMV4gzBs3DgLFcmlAs5iV0cCLf9M',
    appId: '1:1086429205347:web:70a97e7b825dda1dfcf956',
    messagingSenderId: '1086429205347',
    projectId: 'test-fire-33193',
    authDomain: 'test-fire-33193.firebaseapp.com',
    storageBucket: 'test-fire-33193.appspot.com',
    measurementId: 'G-DB418RMRSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrICbdpq8FzHY40x0n2dJ7FldV0HATFs4',
    appId: '1:1086429205347:android:bb47108df7eb8f47fcf956',
    messagingSenderId: '1086429205347',
    projectId: 'test-fire-33193',
    storageBucket: 'test-fire-33193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_us7c3lABthx6ZbMdkaceGZW_JLZFgA0',
    appId: '1:1086429205347:ios:56976598a6b9e5cefcf956',
    messagingSenderId: '1086429205347',
    projectId: 'test-fire-33193',
    storageBucket: 'test-fire-33193.appspot.com',
    iosClientId:
        '1086429205347-aq314gbtsuv82k71ugkg6kh3q7547laj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStep4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_us7c3lABthx6ZbMdkaceGZW_JLZFgA0',
    appId: '1:1086429205347:ios:56976598a6b9e5cefcf956',
    messagingSenderId: '1086429205347',
    projectId: 'test-fire-33193',
    storageBucket: 'test-fire-33193.appspot.com',
    iosClientId:
        '1086429205347-aq314gbtsuv82k71ugkg6kh3q7547laj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStep4',
  );
}
